---
- hosts: all
 # remote_user: cc
  become: yes
  become_user: root
  tasks:
   - name: Make the Swap inactive
     ansible.builtin.shell:
      cmd: swapoff -a
   - name: Remove Swap entry from /etc/fstab.
     lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent
   - name: Installing Prerequisites for Kubernetes
     apt:
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - vim
         - software-properties-common
       state: present
   - name: Add Docker’s official GPG key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
   - name: Add Docker Repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
       state: present
       filename: docker
       mode: 0600
   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
       update_cache: yes
   - name: Install Docker Engine.
     apt:
       name: docker.io
       state: present
   - name: Enable service docker, and enable persistently
     service:
       name: docker
       enabled: yes
   - name: Add Google official GPG key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

       #- name: Add gpg key
       #ansible.builtin.shell:
       #cmd: sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

       #- name: Add gpg key
       #ansible.builtin.shell:
       #cmd: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
   
   - name: Add Kubernetes Repository
     apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
       filename: kubernetes
       mode: 0600

   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
       update_cache: yes

   - name: stop containrd
     ansible.builtin.shell:
       cmd: systemctl stop containerd; rm -rf /etc/containerd/config.toml; systemctl start containerd #sed -i 's/cri//g' /etc/containerd/config.toml; systemctl start containerd

   - name: pause for 59 secs
     pause:
       seconds: 59

   #- name: install new version of containerd
   #  ansible.builtin.shell:
   #    cmd: systemctl start containerd; wget https://github.com/containerd/containerd/releases/download/v1.6.12/containerd-1.6.12-linux-amd64.tar.gz; tar -xvf containerd-1.6.12-linux-amd64.tar.gz; cd bin; cp * /usr/bin/; systemctl start containerd

   #- name: pause for 59 secs
   #  pause:
   #    seconds: 59
   
   - name: Configure Docker Daemon
     copy:
       dest: "/etc/docker/daemon.json"
       content: |
         {
                "exec-opts": ["native.cgroupdriver=systemd"],
                "log-driver": "json-file",
                "log-opts": {
                  "max-size": "100m"
              },
              "storage-driver": "overlay2"
         }

   - name: Reload Docker Daemon
     ansible.builtin.shell:
       cmd: systemctl daemon-reload & systemctl restart docker

   - name: pause for 59 secs
     pause:
       seconds: 59

   - name: change containerd.sock permission
     ansible.builtin.shell:
       cmd: chmod 777 /var/run/containerd/containerd.sock

   - name: change containerd.sock permission
     ansible.builtin.shell:
       cmd: chmod 777 /var/run/docker.sock
   
   - name: Installing Kubernetes Cluster Packages.
     apt:
       name:
         - kubeadm
         - kubectl
         - kubelet #=1.25.5-00
       state: present
   - name: Enable service kubelet, and enable persistently
     service:
       name: kubelet
       enabled: yes
   - name: Add the master node hostname
     ansible.builtin.shell:
       cmd: 'echo "{{ hostname }} kubemaster" >> /etc/hosts'

   - name: Disable FW
     ansible.builtin.shell:
       cmd: ufw disable
   - name: Flush iptables
     ansible.builtin.shell:
       cmd: iptables -F
